check if compute AZ is available
openshift/cluster-api-provider-openstack pull request #143
Opened 2020-12-10 21:56 UTC by EmilienM

Before creating a machine in a given AZ, it'll check that the AZ
actually exists and is available.

JIRA: https://issues.redhat.com/browse/OSASINFRA-1848

Signed-off-by: Emilien Macchi <emilien@redhat.com>

2020-12-10 22:01 UTC, EmilienM commented
/label platform/openstack
/assign EmilienM
/cc pierreprinetti mandre

2020-12-12 14:54 UTC, EmilienM commented
/retest

2020-12-15 00:38 UTC, EmilienM commented
/retest

2020-12-15 08:59 UTC, mandre requested changes

2020-12-15 08:59 UTC, mandre commented on pkg/cloud/openstack/clients/machineservice.go
> +	return fmt.Errorf("could not find compute availability zone: %s", azName)
The CI failure is legit. The worker nodes didn't join the cluster and [CAPO logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-api-provider-openstack/143/pull-ci-openshift-cluster-api-provider-openstack-master-e2e-openstack/1338644663849979904/artifacts/e2e-openstack/pods/openshift-machine-api_machine-api-controllers-59588cfb5d-r7hs2_machine-controller.log) show:
```
E1215 01:06:37.174559       1 actuator.go:574] Machine error 2cjl5vir-6817d-s77pk-worker-0-s9n24: Machine validation failed: could not find compute availability zone: 
```

I suggest you exit early if `azName` is an empty string.

2020-12-15 08:59 UTC, mandre commented on pkg/cloud/openstack/clients/machineservice.go
> +// TODO: remove that function once we bump gophercloud/utils that containers this helper.
How about doing it now? https://github.com/gophercloud/utils/pull/130 has merged, we can bump `gophercloud/utils`.

2020-12-15 08:59 UTC, mandre commented on pkg/cloud/openstack/clients/machineservice.go
> +	zones, err := ListAvailableAvailabilityZones(is.computeClient)
```suggestion
	if azName == "" {
		return nil
	}
	zones, err := ListAvailableAvailabilityZones(is.computeClient)
```

2020-12-15 09:59 UTC, mandre commented
Also, this needs a valid BZ because we're in feature freeze and only patches fixing a bug are allowed to merge.

2020-12-15 16:25 UTC, EmilienM commented on pkg/cloud/openstack/clients/machineservice.go
> +// TODO: remove that function once we bump gophercloud/utils that containers this helper.
no we can't because it requires a new gophercloud and this is a nightmare, see https://github.com/openshift/cluster-api-provider-openstack/pull/126/files

2020-12-16 08:13 UTC, mandre commented on pkg/cloud/openstack/clients/machineservice.go
> +// TODO: remove that function once we bump gophercloud/utils that containers this helper.
Gotcha.

2020-12-16 08:15 UTC, mandre reviewed
Nice, this is passing CI now. All that is missing is a related BZ so that this can merge.

2020-12-16 19:14 UTC, EmilienM commented
/bugzilla refresh

2020-12-16 19:15 UTC, EmilienM commented
@mandre done! thanks for your review.

2020-12-17 12:36 UTC, mandre approved these changes
/lgtm
/approve

2020-12-17 13:20 UTC, pierreprinetti commented
/bugzilla refresh

2020-12-17 13:20 UTC, pierreprinetti commented
/label platform/openstack

2020-12-17 15:22 UTC, merged