Update gogo/protobuf to v1.3.2
openshift/cluster-api-provider-openstack pull request #161
Opened 2021-02-03 16:26 UTC by EmilienM

gogo/protobuf@v1.3.2 fixes https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3121

Ref: https://issues.redhat.com/browse/OCPBUGSM-24279

2021-02-03 16:58 UTC, iamemilio commented
/lgtm

2021-02-03 16:59 UTC, iamemilio commented
/approve
/hold until passing

2021-02-04 10:45 UTC, mdbooth commented
/hold

This is hopefully just precautionary as I'm honestly not sure what I'm looking at here. However, I have 2 concerns about this patch:

1. The revendor of gogo/protobuf doesn't seem to contain the CVE fix: https://github.com/gogo/protobuf/commit/b03c65ea87cdc3521ede29f62fe3ce239267c1bc
2. I'm not sure about the various dependent mod updates

Presumably (2) is just transitive updates from gogo/protobuf, but I'd like to convince myself of that. The first one seems problematic, though.

2021-02-04 10:48 UTC, mdbooth requested changes

2021-02-04 10:48 UTC, mdbooth commented on vendor/github.com/gogo/protobuf/proto/text_parser.go
> +		return string(rune(i)), s, nil
This doesn't seem to be the actual CVE fix: https://github.com/gogo/protobuf/commit/b03c65ea87cdc3521ede29f62fe3ce239267c1bc

Going to try to work out what's going on here, as the explicit request was to bump to v1.3.2, which you've done.

2021-02-04 10:57 UTC, pierreprinetti commented on vendor/github.com/gogo/protobuf/proto/text_parser.go
> +		return string(rune(i)), s, nil
`go mod vendor` performs some treeshaking on a subpackage-basis.

The fix you linked refers to the file `plugin/unmarshal/unmarshal.go` which is not present in the `vendor/github.com/gogo/protobuf` folder. This means that the fix applies to some code that is not used in CAPO

2021-02-04 10:59 UTC, pierreprinetti commented on vendor/github.com/gogo/protobuf/proto/text_parser.go
> +		return string(rune(i)), s, nil
Bumping the dependency prevents any further code change to introduce the vulnerable version of the affected `plugin/unmarshal` subpackage; however it can be deferred to 4.8 at this point.

2021-02-04 11:16 UTC, mdbooth commented on vendor/github.com/gogo/protobuf/proto/text_parser.go
> +		return string(rune(i)), s, nil
What seems to be going on here is that the vendor copy doesn't contain the plugin/unmarshal/unmarshal.go at all, so doesn't contain the CVE fix. This discussion seems relevant: https://github.com/golang/go/issues/26366#issuecomment-405683150 . If I'm reading that correctly, the go mod vendor is only pulling in files from the target which are actually used to build. If that's the case then presumably:

* This patch is correctly updating the module version to 1.3.2
* It turns out it's not critical as we're not touching the CVE code anyway

2021-02-04 11:56 UTC, mdbooth commented
This patch correctly bumps gogo/protobuf to v1.3.2.

HOWEVER, because the CVE is in a code generator, this isn't how this problem needs to be addressed. We need to address the problem in *every package which we vendor which generates code with protobuf*. As per my original supposition that seems to be almost everything. Grepping for instances of generated vulnerable code reveals 51 instances:

```
$ git grep -l "if skippy < 0 {"
vendor/k8s.io/api/admission/v1/generated.pb.go
vendor/k8s.io/api/admission/v1beta1/generated.pb.go
vendor/k8s.io/api/admissionregistration/v1/generated.pb.go
vendor/k8s.io/api/admissionregistration/v1beta1/generated.pb.go
vendor/k8s.io/api/apps/v1/generated.pb.go
vendor/k8s.io/api/apps/v1beta1/generated.pb.go
vendor/k8s.io/api/apps/v1beta2/generated.pb.go
vendor/k8s.io/api/authentication/v1/generated.pb.go
vendor/k8s.io/api/authentication/v1beta1/generated.pb.go
vendor/k8s.io/api/authorization/v1/generated.pb.go
vendor/k8s.io/api/authorization/v1beta1/generated.pb.go
vendor/k8s.io/api/autoscaling/v1/generated.pb.go
vendor/k8s.io/api/autoscaling/v2beta1/generated.pb.go
vendor/k8s.io/api/autoscaling/v2beta2/generated.pb.go
vendor/k8s.io/api/batch/v1/generated.pb.go
vendor/k8s.io/api/batch/v1beta1/generated.pb.go
vendor/k8s.io/api/batch/v2alpha1/generated.pb.go
vendor/k8s.io/api/certificates/v1/generated.pb.go
vendor/k8s.io/api/certificates/v1beta1/generated.pb.go
vendor/k8s.io/api/coordination/v1/generated.pb.go
vendor/k8s.io/api/coordination/v1beta1/generated.pb.go
vendor/k8s.io/api/core/v1/generated.pb.go
vendor/k8s.io/api/discovery/v1alpha1/generated.pb.go
vendor/k8s.io/api/discovery/v1beta1/generated.pb.go
vendor/k8s.io/api/events/v1/generated.pb.go
vendor/k8s.io/api/events/v1beta1/generated.pb.go
vendor/k8s.io/api/extensions/v1beta1/generated.pb.go
vendor/k8s.io/api/flowcontrol/v1alpha1/generated.pb.go
vendor/k8s.io/api/imagepolicy/v1alpha1/generated.pb.go
vendor/k8s.io/api/networking/v1/generated.pb.go
vendor/k8s.io/api/networking/v1beta1/generated.pb.go
vendor/k8s.io/api/node/v1alpha1/generated.pb.go
vendor/k8s.io/api/node/v1beta1/generated.pb.go
vendor/k8s.io/api/policy/v1beta1/generated.pb.go
vendor/k8s.io/api/rbac/v1/generated.pb.go
vendor/k8s.io/api/rbac/v1alpha1/generated.pb.go
vendor/k8s.io/api/rbac/v1beta1/generated.pb.go
vendor/k8s.io/api/scheduling/v1/generated.pb.go
vendor/k8s.io/api/scheduling/v1alpha1/generated.pb.go
vendor/k8s.io/api/scheduling/v1beta1/generated.pb.go
vendor/k8s.io/api/settings/v1alpha1/generated.pb.go
vendor/k8s.io/api/storage/v1/generated.pb.go
vendor/k8s.io/api/storage/v1alpha1/generated.pb.go
vendor/k8s.io/api/storage/v1beta1/generated.pb.go
vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.pb.go
vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
vendor/k8s.io/apimachinery/pkg/api/resource/quantity_proto.go
vendor/k8s.io/apimachinery/pkg/apis/meta/v1/generated.pb.go
vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1/generated.pb.go
vendor/k8s.io/apimachinery/pkg/runtime/generated.pb.go
vendor/k8s.io/apimachinery/pkg/util/intstr/generated.pb.go
```

2021-02-15 08:45 UTC, mandre reviewed
This needs a backport of https://github.com/kubernetes/kubernetes/pull/98477 to `release-1.20` and bumping the affected k8s modules.

2021-05-28 02:18 UTC, closed without merging